awk '
/export const getSalesOrderById = async/ {
    print "export const getSalesOrderSummary = async (id: number) => {"
    print "  const salesOrder: any = (await salesOrderRepository.getSalesOrderById(id))?.get({ plain: true });"
    print "  if (!salesOrder) return null;"
    print ""
    print "  const calculations = salesOrderProductRepository.getTotalsOfSalesOrderProducts(salesOrder.salesOrderProducts);"
    print "  const totalAdvancedDeposit = _.sumBy(salesOrder.advancedDeposits, (e: any) => Number(e.amount));"
    print ""
    print "  const totalItems = salesOrder.salesOrderProducts?.length || 0;"
    print "  const totalSlabs = salesOrder.salesOrderProducts?.filter((p: any) => p.inventoryProduct?.slabId).length || 0;"
    print "  const totalSqft = salesOrder.salesOrderProducts?.reduce((acc: number, p: any) => {"
    print "      if (p.inventoryProduct?.slab) {"
    print "          return acc + ((p.inventoryProduct.slab.receivingLength * p.inventoryProduct.slab.receivingWidth) / 144);"
    print "      }"
    print "      return acc;"
    print "  }, 0) || 0;"
    print ""
    print "  const numPickLists = salesOrder.loadingOrders?.length || 0;"
    print "  const numLoadingOrders = salesOrder.actualLoadingOrders?.length || 0;"
    print ""
    print "  return {"
    print "    customer: salesOrder.customer,"
    print "    financials: {"
    print "      subTotal: calculations.soReceiving.subTotal,"
    print "      tax: calculations.soReceiving.tax,"
    print "      total: calculations.soReceiving.total,"
    print "      advancedDeposit: totalAdvancedDeposit,"
    print "      balanceDue: calculations.soReceiving.total - totalAdvancedDeposit"
    print "    },"
    print "    quantities: {"
    print "      totalItems,"
    print "      totalSlabs,"
    print "      totalSqft: Number(totalSqft.toFixed(2))"
    print "    },"
    print "    logistics: {"
    print "      pickLists: numPickLists,"
    print "      loadingOrders: numLoadingOrders"
    print "    },"
    print "    salesRep: salesOrder.salesRep,"
    print "    createdBy: salesOrder.createdBy,"
    print "    status: salesOrder.status,"
    print "    soNumber: salesOrder.soNumber,"
    print "    clientSoNumber: salesOrder.clientSoNumber"
    print "  };"
    print "};"
    print ""
}
{ print }
' src/services/salesOrder.service.ts > temp.ts && mv temp.ts src/services/salesOrder.service.ts
