import { DataTypes, Op } from "sequelize";
import { sequelize } from "../config/database";
import { PAYEE_TYPE, PAYMENT_METHOD, PAYMENT_STATUS, PAYMENT_TYPE } from "../constants/tableTypes";
import User from "./user.model";
import Client from "./client.model";
import LedgerAccount from "./ledgerAccount.model";

const Payment = sequelize.define(
  "Payment",
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    paymentType: {
      type: DataTypes.ENUM(...Object.values(PAYMENT_TYPE)), // incoming = received, outgoing = made
      allowNull: false,
    },
    payeeId: {
      type: DataTypes.INTEGER,
      allowNull: false, // The ID of the entity receiving/sending payment
    },
    payeeType: {
      type: DataTypes.ENUM(...Object.values(PAYEE_TYPE)), // Future-proofing
      allowNull: false,
    },
    amount: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: false,
    },
    paymentMethod: {
      type: DataTypes.ENUM(...Object.values(PAYMENT_METHOD)),
      allowNull: false,
    },
    clientTransactionNo: {
      type: DataTypes.INTEGER,
      allowNull: true, // not null handled by hook
    },
    transactionCode: {
      type: DataTypes.STRING,
      allowNull: true, // will be generated by hook
    },
    status: {
      type: DataTypes.ENUM(...Object.values(PAYMENT_STATUS)),
      defaultValue: PAYMENT_STATUS.PENDING,
    },
    remark: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    referenceNo: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    referenceDate: {
      type: DataTypes.DATEONLY,
      allowNull: true,
    },
    paymentFor: {
      type: DataTypes.ENUM('ADVANCED_DEPOSIT'),
      allowNull: true
    },
    paymentForId: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    userId: {
      type: DataTypes.INTEGER,
      references: {
        model: User,
        key: "id",
      },
      onUpdate: "CASCADE",
      onDelete: "RESTRICT",
    },
    clientId: {
      type: DataTypes.INTEGER,
      references: {
        model: Client,
        key: "id",
      },
      onUpdate: "CASCADE",
      onDelete: "RESTRICT",
    },
    accountId: {
      type: DataTypes.INTEGER,
      references: {
        model: LedgerAccount,
        key: "id",
      },
      onUpdate: "CASCADE",
      onDelete: "RESTRICT",
    }
  },
  {
    tableName: "payments",
    timestamps: true,
    indexes: [
      {
        unique: true,
        fields: ["clientId", "clientTransactionNo"],
      },
      {
        unique: true,
        fields: ["transactionCode", 'clientId'],
      },
    ],
  }
);

// 🔹 Hook: Auto-Increment `clientInvoiceNumber` based on `clientId`
Payment.beforeCreate(async (payment: any) => {
  if (!payment.clientId) {
    throw new Error("Client ID is required to generate transaction number");
  }

  const lastSIPLAccordingToPO: any = await Payment.findOne({
    where: { clientId: payment.clientId },
    order: [["clientTransactionNo", "DESC"]],
  });

  payment.clientTransactionNo = lastSIPLAccordingToPO ? lastSIPLAccordingToPO.clientTransactionNo + 1 : 1;

  // Generate transaction code based on Ledger Account name
  if (payment.accountId) {
    const ledgerAccount: any = await LedgerAccount.findByPk(payment.accountId);
    if (ledgerAccount && ledgerAccount.name) {
      // Get first 2-3 characters from the account name
      const accountPrefix = ledgerAccount.name.substring(0, 3).toUpperCase();

      // Find the last transaction code with this prefix
      const lastPayment: any = await Payment.findOne({
        where: {
          clientId: payment.clientId,
          transactionCode: {
            [Op.like]: `${accountPrefix}%`
          }
        },
        order: [["transactionCode", "DESC"]],
      });

      let sequenceNumber = 1;
      if (lastPayment && lastPayment.transactionCode) {
        // Extract the number from the last transaction code
        const lastNumber = parseInt(lastPayment.transactionCode.replace(accountPrefix, ''));
        if (!isNaN(lastNumber)) {
          sequenceNumber = lastNumber + 1;
        }
      }

      payment.transactionCode = `${accountPrefix}${sequenceNumber.toString().padStart(3, '0')}`;
    }
  }
});

// Scope configuration for Payment model
(Payment as any).scopeConfig = {
  client: true,
  location: false,
};

export default Payment;



