INSERT INTO accounts (sub_account_types_id, account_types_id, account_name, account_balance, can_delete, opening_balance_date, created_at, updated_at)
VALUES 
(1, 1, 'Cash and Cash Equivalents', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'Investments', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'Restricted Cash and Investments', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 'Accounts, Notes and Loans Receivable', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 'Contracts with Customers', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 'Nontrade and Other Receivables', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'Retail Related Inventory, Merchandise', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'Raw Material, Parts and Supplies', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'Work in Process', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'Finished Goods', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'Other Inventory, Gross ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 'Prepaid Expense ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 'Accrued Income', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 'Additional Assets', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Land and Land Improvements', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Buildings, Structures and Improvements', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Machinery and Equipment', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Furniture and Fixtures ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Right of Use Assets (Classified as PP&E)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Additional Property, Plant and Equipment', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 'Construction In Progress', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Intellectual Property', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Computer Software', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Trade and Distribution Assets', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Contracts and Rights', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Right to Use Assets (Classified as Intangible)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Crypto Assets', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Other Intangible Assets', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 'Acquisition In Progress', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 2, 'Trade Payables', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 2, 'Dividends Payable', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 2, 'Interest Payable', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 2, 'Other Payables', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 'Accrued Expenses', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 'Accrued Taxes (Other Than Payroll)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 'Deferred Income and Refund Liabilities', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 'Percentage of Completion (Liability Accounts)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 'Other Liabilities', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 'Notes Payable', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 'Loans Payable', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 'Bonds (Debentures)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 'Other Debts and Borrowings', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 'Lease Obligations', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 'Derivative Liability', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 2, 'Customer Related Contingencies', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 2, 'Litigation and Regulatory', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 2, 'Additional Provisions', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 3, 'Equity at Par', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 3, 'Additional Paid-In Capital', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 3, 'Appropriated', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 3, 'Unappropriated', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 3, 'Deficit', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 3, 'In Suspense', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 3, 'Foreign Currency Translation Adjustment', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 3, 'AOCI, Cash Flow Hedge, Cumulative Gain (Loss)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 3, 'Remeasurements Available-For-Sale Financial Assets', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 3, 'Remeasurement Of Defined Benefit Plans ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 3, 'Additional AOCI Items', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 3, 'ESOP Related Items ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 3, 'Subscribed Stock Receivables ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 3, 'Treasury Stock', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 3, 'Miscellaneous Equity ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 4, 'Goods', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 4, 'Services', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 4, 'Products', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 4, 'Services', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 4, 'Variable Consideration', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 4, 'Consideration Paid (Payable) To Customers', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 4, 'Other Adjustments', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 5, 'Material and Merchandise', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 5, 'Employee Benefits', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 5, 'Services', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 5, 'Rent, Depreciation, Amortization and Depletion', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 5, 'Cost Of Sales', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 5, 'Selling, General and Administrative ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 5, 'Uncollectible Accounts Expense (Reversal)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 6, 'Other Revenue', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 6, 'Other Expenses', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Foreign Currency Transaction Gain (Loss)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Gain (Loss) On Investments', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Gain (Loss) On Derivatives', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Crypto Asset Gain (Loss)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Gain (Loss) On Disposal Of Assets ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Debt Related Gain (Loss)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Impairment Loss ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 6, 'Other Gains and (Losses)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Real Estate Taxes and Insurance ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Highway (Road) Taxes and Tolls', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Direct Tax and License Fees', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Excise and Sales Taxes', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Customs Fees and Duties (Not Classified As Sales Or Excise)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'General Insurance Expense', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Administrative Fees (Revenue Stamps)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Fines and Penalties', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Miscellaneous Taxes', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 6, 'Other Taxes and Fees', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 7, 'Intercompany Balances (Eliminated In Consolidation)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 7, 'Related Party Balances (Reported Or Disclosed) ', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 7, 'Intercompany Investments', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 7, 'Intercompany Balances (Eliminated In Consolidation)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 7, 'Related Party Balances (Reported Or Disclosed)', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 7, 'Intercompany and Related Party Income', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 7, 'Intercompany and Related Party Expenses', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 7, 'Income (Loss) From Equity Method Investments', 0, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);