-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 07:41:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stone_design
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stone_design
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stone_design` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stone_design` ;

-- -----------------------------------------------------
-- Table `stone_design`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NULL DEFAULT NULL,
  `client_password` VARCHAR(255) NULL DEFAULT NULL,
  `client_email` VARCHAR(255) NULL DEFAULT NULL,
  `client_location` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` CHAR(36) NULL DEFAULT NULL,
  `client_location_short_name` VARCHAR(100) NULL DEFAULT NULL,
  `client_type` VARCHAR(100) NULL DEFAULT NULL,
  `client_address` VARCHAR(255) NULL DEFAULT NULL,
  `client_country` VARCHAR(100) NULL DEFAULT NULL,
  `client_city` VARCHAR(100) NULL DEFAULT NULL,
  `pincode` VARCHAR(20) NULL DEFAULT NULL,
  `client_tax` VARCHAR(50) NULL DEFAULT NULL,
  `client_price_level` INT NULL DEFAULT NULL,
  `payment_terms` VARCHAR(100) NULL DEFAULT NULL,
  `client_license_number` VARCHAR(100) NULL DEFAULT NULL,
  `user_count` INT NULL DEFAULT NULL,
  UNIQUE INDEX `client_id` (`client_id` ASC) VISIBLE,
  UNIQUE INDEX `client_email` (`client_email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `userid` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userid` (`userid` ASC) VISIBLE,
  INDEX `idx_user_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`client_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`client_users` (
  `client_user_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`client_user_id`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `client_users_ibfk_57`
    FOREIGN KEY (`client_id`)
    REFERENCES `stone_design`.`clients` (`client_id`),
  CONSTRAINT `client_users_ibfk_58`
    FOREIGN KEY (`user_id`)
    REFERENCES `stone_design`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `type` ENUM('Slab', 'Pavers', 'Bench', 'Table', 'Sink', 'Mirror') NOT NULL,
  `base_color` ENUM('Black', 'Beige', 'Blue', 'Dark Blue', 'Brown', 'Pink', 'Gold', 'Gray', 'Crimson', 'Red', 'Dark Red', 'Mute Red', 'White', 'Yellow', 'Green', 'Sea Green', 'Mute sea green', 'light Green') NULL DEFAULT NULL,
  `origin` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `category` ENUM('GRANITE', 'LIMESTONE', 'MARBLE', 'QUARTZ', 'QUARTZITE', 'SOAPSTONE') NULL DEFAULT NULL,
  `alternative_name` VARCHAR(255) NULL DEFAULT NULL,
  `kind` ENUM('Stock', 'Non-stock') NOT NULL,
  `sub_category` VARCHAR(255) NULL DEFAULT NULL,
  `groups_all` VARCHAR(255) NULL DEFAULT NULL,
  `finish` VARCHAR(255) NULL DEFAULT NULL,
  `thickness` VARCHAR(255) NULL DEFAULT NULL,
  `serial_name` VARCHAR(255) NULL DEFAULT NULL,
  `uom_group` ENUM('lb', 'in', 'CF', 'CM', 'SF', 'Kg', 'SQM', 'CBM', 'EA') NOT NULL,
  `weight` VARCHAR(255) NULL DEFAULT NULL,
  `single_slab` VARCHAR(255) NOT NULL,
  `bundle` VARCHAR(255) NULL DEFAULT NULL,
  `price_range` ENUM('low', 'mid', 'high', 'very high') NULL DEFAULT NULL,
  `gl_inventory_link_account` VARCHAR(255) NULL DEFAULT NULL,
  `gl_income_account` VARCHAR(255) NULL DEFAULT NULL,
  `gl_cost_goods_account` VARCHAR(255) NULL DEFAULT NULL,
  `safety_stock` VARCHAR(255) NULL DEFAULT NULL,
  `reorder_quantity` VARCHAR(255) NULL DEFAULT NULL,
  `lead_time` VARCHAR(255) NULL DEFAULT NULL,
  `assigned_time` ENUM('A1', 'A2', 'A3', 'B1', 'B2', 'B3') NULL DEFAULT NULL,
  `preferred_supplier` VARCHAR(255) NULL DEFAULT NULL,
  `manufacture` VARCHAR(255) NULL DEFAULT NULL,
  `purchase_unit` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_product` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_sku` VARCHAR(255) NULL DEFAULT NULL,
  `avr_estimate_cost` VARCHAR(255) NULL DEFAULT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  `instructions` VARCHAR(255) NULL DEFAULT NULL,
  `disclaimer` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `p_mfg_not_supplier` TINYINT(1) NULL DEFAULT NULL,
  `generic_product` TINYINT(1) NULL DEFAULT NULL,
  `customer_select_slab` TINYINT(1) NULL DEFAULT NULL,
  `non_serialized` TINYINT(1) NULL DEFAULT NULL,
  `invisible` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_name_2` (`product_name` ASC) VISIBLE,
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `stone_design`.`client_users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`vendors` (
  `vendor_id` INT NOT NULL AUTO_INCREMENT,
  `vendor_name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `vendor_type` ENUM('National', 'International') NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `vendor_since` VARCHAR(255) NOT NULL,
  `primary_phone_no` VARCHAR(255) NOT NULL,
  `secondary_phone_no` VARCHAR(255) NULL DEFAULT NULL,
  `landline_no` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `accounting_email` VARCHAR(255) NULL DEFAULT NULL,
  `remit_address` VARCHAR(255) NULL DEFAULT NULL,
  `remit_suite` VARCHAR(255) NULL DEFAULT NULL,
  `remit_city` VARCHAR(255) NULL DEFAULT NULL,
  `remit_state` VARCHAR(255) NULL DEFAULT NULL,
  `remit_zip` INT NULL DEFAULT NULL,
  `remit_country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `shipping_address` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_suite` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_city` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_state` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_zip` INT NULL DEFAULT NULL,
  `shipping_country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `payment_terms` VARCHAR(255) NULL DEFAULT NULL,
  `currency` VARCHAR(255) NULL DEFAULT NULL,
  `default_expense_account` VARCHAR(255) NULL DEFAULT NULL,
  `default_payment_method` VARCHAR(255) NULL DEFAULT NULL,
  `account` VARCHAR(255) NULL DEFAULT NULL,
  `ein_number` VARCHAR(255) NULL DEFAULT NULL,
  `memo_on_check` VARCHAR(255) NULL DEFAULT NULL,
  `generic_vendor` TINYINT(1) NULL DEFAULT NULL,
  `form_us_vendor` TINYINT(1) NULL DEFAULT NULL,
  `freight_carrie` TINYINT(1) NULL DEFAULT NULL,
  `sub_contractor` TINYINT(1) NULL DEFAULT NULL,
  `allow_vendor_login` TINYINT(1) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`vendor_id`),
  UNIQUE INDEX `primary_phone_no` (`primary_phone_no` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`locations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `suite` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `zip` INT NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `purchase_location` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  UNIQUE INDEX `location` (`location` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`purchase_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`purchase_orders` (
  `purchase_order_id` INT NOT NULL AUTO_INCREMENT,
  `po` INT NOT NULL,
  `po_date` DATETIME NOT NULL,
  `supplier_so` VARCHAR(255) NULL DEFAULT NULL,
  `required_ship_date` DATETIME NULL DEFAULT NULL,
  `eta_date` DATETIME NULL DEFAULT NULL,
  `po_expire_date` DATETIME NULL DEFAULT NULL,
  `container` VARCHAR(255) NULL DEFAULT NULL,
  `delivery_date` ENUM('Pickup', 'Delivery', 'Other') NULL DEFAULT NULL,
  `shipment_terms` ENUM('Prepaid', 'Prepaid & Add', 'Collect', 'Prepaid & COD', 'Add & COD', 'Collect & COD', 'Credit 45', 'CAD', 'Consigment') NULL DEFAULT NULL,
  `payment_term` INT NOT NULL,
  `vessel` VARCHAR(255) NULL DEFAULT NULL,
  `air_bill` INT NULL DEFAULT NULL,
  `planned_ex_factorydate` DATETIME NULL DEFAULT NULL,
  `ex_factorydate` DATETIME NULL DEFAULT NULL,
  `departure_port` VARCHAR(255) NULL DEFAULT NULL,
  `etd_Port` VARCHAR(255) NULL DEFAULT NULL,
  `arrival_port` VARCHAR(255) NULL DEFAULT NULL,
  `eta_port` DATETIME NULL DEFAULT NULL,
  `discharge_port` VARCHAR(255) NULL DEFAULT NULL,
  `wiring_instruction` VARCHAR(255) NULL DEFAULT NULL,
  `printed_notes` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `special_instruction` VARCHAR(255) NULL DEFAULT NULL,
  `po_term_select` VARCHAR(255) NULL DEFAULT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  `other_charges` ENUM('Consignment Payable', 'Delivery', 'Fabrication & Installation', 'FINANCE CHARGE', 'Insurance', 'Pre-migration Return/Pruchase', 'Vendor Credit') NULL DEFAULT NULL,
  `account_number` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `charge` FLOAT NULL DEFAULT NULL,
  `status` ENUM('OPEN', 'CLOSE', 'UNAPPROVED') NOT NULL DEFAULT 'OPEN',
  `supplier_id` INT NOT NULL,
  `purchase_location_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `freight_forwarder` INT NULL DEFAULT NULL,
  `purchase_order_status` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`purchase_order_id`),
  INDEX `purchase_location_id` (`purchase_location_id` ASC) VISIBLE,
  INDEX `location_id` (`location_id` ASC) VISIBLE,
  INDEX `fk_freight_forwarder` (`freight_forwarder` ASC) VISIBLE,
  CONSTRAINT `fk_freight_forwarder`
    FOREIGN KEY (`freight_forwarder`)
    REFERENCES `stone_design`.`vendors` (`vendor_id`),
  CONSTRAINT `purchase_orders_ibfk_2`
    FOREIGN KEY (`purchase_location_id`)
    REFERENCES `stone_design`.`locations` (`location_id`),
  CONSTRAINT `purchase_orders_ibfk_3`
    FOREIGN KEY (`location_id`)
    REFERENCES `stone_design`.`locations` (`location_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`po_supplier_invoice_mapper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`po_supplier_invoice_mapper` (
  `po_supplier_invoice_mapper_id` INT NOT NULL AUTO_INCREMENT,
  `purchase_order_id` INT NOT NULL,
  `total_product_charges` FLOAT NULL DEFAULT NULL,
  `other_charges_total` FLOAT NULL DEFAULT NULL,
  `final_total_charges` FLOAT NULL DEFAULT NULL,
  `transaction` VARCHAR(255) NULL DEFAULT NULL,
  `invoice` VARCHAR(255) NULL DEFAULT NULL,
  `invoice_date` DATE NOT NULL,
  `ship_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `status` ENUM('ACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `receiving_inventory` TINYINT(1) NULL DEFAULT '0',
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `transaction_status` ENUM('SIPL CREATED', 'SLAB ADDED', 'FREIGHT ADDED', 'CONTAINER ADDED', 'INVENTORY RECEIVED') NULL DEFAULT 'SIPL CREATED',
  `product_id` INT NULL DEFAULT NULL,
  `receive_inventory_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`po_supplier_invoice_mapper_id`),
  INDEX `purchase_order_id` (`purchase_order_id` ASC) VISIBLE,
  INDEX `fk_product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `stone_design`.`products` (`product_id`),
  CONSTRAINT `po_supplier_invoice_mapper_ibfk_1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `stone_design`.`purchase_orders` (`purchase_order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`account_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`account_types` (
  `account_types_id` INT NOT NULL AUTO_INCREMENT,
  `account_type` ENUM('Assets', 'Liabilities', 'Revenue', 'Expenses', 'Equity Including Portion Attributable to Noncontrolling Interest', 'Other (Non-Operating) Income and Expenses', 'Intercompany and Related Party Accounts') NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`account_types_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sub_account_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sub_account_types` (
  `sub_account_types_id` INT NOT NULL AUTO_INCREMENT,
  `account_types_id` INT NULL DEFAULT NULL,
  `sub_account_type` ENUM('Cash and Financial Assets', 'Receivables and Contracts', 'Inventory', 'Accruals and Additional Assets', 'Property, Plant and Equipment', 'Intangible Assets (Excluding Goodwill)', 'Goodwill', 'Payables', 'Accruals, Deferrals and Other Liabilities', 'Financial Labilities', 'Commitments and Contingencies', 'Equity, Attributable to Parent', 'Retained Earnings (Accumulated Deficit)', 'Accumulated Other Comprehensive Income (Loss)', 'Other Equity Items', 'Equity, Attributable to Noncontrolling Interest', 'Recognized Point Of Time', 'Recognized Over Time', 'Adjustments', 'Expenses Classified By Nature', 'Expenses Classified By Function', 'Other Revenue and Expenses', 'Gains and Losses', 'Taxes (Other Than Income and Payroll) and Fees', 'Income Tax Expense (Benefit)', 'Intercompany and Related Party Assets', 'Intercompany and Related Party Liabilities', 'Intercompany and Related Party Income and Expense') NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sub_account_types_id`),
  INDEX `account_types_id` (`account_types_id` ASC) VISIBLE,
  CONSTRAINT `sub_account_types_ibfk_1`
    FOREIGN KEY (`account_types_id`)
    REFERENCES `stone_design`.`account_types` (`account_types_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NOT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `print_name` VARCHAR(255) NULL DEFAULT NULL,
  `parent_customer` VARCHAR(255) NULL DEFAULT NULL,
  `primary_phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `secondary_phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `landline_number` VARCHAR(255) NULL DEFAULT NULL,
  `acc_email` VARCHAR(255) NULL DEFAULT NULL,
  `emails` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `suite` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `zip` VARCHAR(255) NULL DEFAULT NULL,
  `s_address` VARCHAR(255) NULL DEFAULT NULL,
  `s_unit` VARCHAR(255) NULL DEFAULT NULL,
  `s_city` VARCHAR(255) NULL DEFAULT NULL,
  `s_zip` VARCHAR(255) NULL DEFAULT NULL,
  `s_state` VARCHAR(255) NULL DEFAULT NULL,
  `p_sales_person` VARCHAR(255) NULL DEFAULT NULL,
  `tax_exempt` VARCHAR(255) NULL DEFAULT NULL,
  `sales_tax` VARCHAR(255) NULL DEFAULT NULL,
  `exempt_certi` VARCHAR(255) NULL DEFAULT NULL,
  `exempt_exipry` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `delivery_notes` VARCHAR(255) NULL DEFAULT NULL,
  `po_required` TINYINT(1) NULL DEFAULT NULL,
  `apply_finance_charges` TINYINT(1) NULL DEFAULT NULL,
  `preferred_way_docs` ENUM('Fax', 'Email', 'Mail', 'Text') NULL DEFAULT NULL,
  `days_grace` VARCHAR(255) NULL DEFAULT NULL,
  `days_hold` VARCHAR(255) NULL DEFAULT NULL,
  `customerSince` DATETIME NULL DEFAULT NULL,
  `ein_number` VARCHAR(255) NULL DEFAULT NULL,
  `country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `s_country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `customer_type` ENUM('Homeowner', 'Architect', 'KB Dealer', 'Designer', 'Fabricator', 'Builder') NULL DEFAULT NULL,
  `payment_terms` ENUM('30', '45', '60', '90', '120', 'COD') NULL DEFAULT NULL,
  `reason` ENUM('Reseller') NULL DEFAULT NULL,
  `price_level` ENUM('Single Slab', 'Bundle', 'Standard') NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT 'ACTIVE',
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `unique_primary_phone_number` (`primary_phone_number` ASC) VISIBLE,
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  INDEX `updated_by` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `customers_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `stone_design`.`client_users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `customers_ibfk_2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `stone_design`.`client_users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`accounts` (
  `accounts_id` INT NOT NULL AUTO_INCREMENT,
  `sub_account_types_id` INT NULL DEFAULT NULL,
  `account_types_id` INT NULL DEFAULT NULL,
  `account_name` VARCHAR(255) NOT NULL,
  `opening_balance_date` DATETIME NULL DEFAULT NULL,
  `account_balance` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `can_delete` TINYINT(1) NOT NULL DEFAULT '0',
  `customer_id` INT NULL DEFAULT NULL,
  `coa_code` VARCHAR(50) NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`accounts_id`),
  UNIQUE INDEX `coa_code` (`coa_code` ASC) VISIBLE,
  INDEX `sub_account_types_id` (`sub_account_types_id` ASC) VISIBLE,
  INDEX `account_types_id` (`account_types_id` ASC) VISIBLE,
  INDEX `fk_customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `accounts_ibfk_1`
    FOREIGN KEY (`sub_account_types_id`)
    REFERENCES `stone_design`.`sub_account_types` (`sub_account_types_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `accounts_ibfk_2`
    FOREIGN KEY (`account_types_id`)
    REFERENCES `stone_design`.`account_types` (`account_types_id`),
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `stone_design`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_type` ENUM('National', 'International') NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `parent_location` VARCHAR(255) NOT NULL,
  `print_name` VARCHAR(255) NULL DEFAULT NULL,
  `language` ENUM('English', 'French', 'Spanish', 'Italian') NULL DEFAULT NULL,
  `parent_supplier` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_since` DATETIME NULL DEFAULT NULL,
  `port` VARCHAR(255) NULL DEFAULT NULL,
  `markup_multiplier` FLOAT NULL DEFAULT NULL,
  `discount` FLOAT NULL DEFAULT NULL,
  `primary_phone_no` VARCHAR(255) NOT NULL,
  `secondary_phone_no` VARCHAR(255) NULL DEFAULT NULL,
  `landline_no` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `accounting_email` VARCHAR(255) NULL DEFAULT NULL,
  `remit_address` VARCHAR(255) NULL DEFAULT NULL,
  `remit_suite` VARCHAR(255) NULL DEFAULT NULL,
  `remit_city` VARCHAR(255) NULL DEFAULT NULL,
  `remit_state` VARCHAR(255) NULL DEFAULT NULL,
  `remit_zip` INT NULL DEFAULT NULL,
  `remit_country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `shipping_address` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_suite` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_city` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_state` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_zip` INT NULL DEFAULT NULL,
  `shipping_country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `delivery_notes` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `payment_term` INT NULL DEFAULT NULL,
  `currency` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`supplier_id`),
  UNIQUE INDEX `supplier_name_2` (`supplier_name` ASC) VISIBLE,
  UNIQUE INDEX `unique_primary_phone_number` (`primary_phone_no` ASC) VISIBLE,
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `suppliers_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `stone_design`.`client_users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sales_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sales_orders` (
  `sales_orders_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `so` INT NOT NULL,
  `so_date` DATE NOT NULL,
  `customer_po` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `ship_to` ENUM('DELIVERY', 'PICKUP') NOT NULL,
  `special_instruction` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `printed_notes` VARCHAR(255) NULL DEFAULT NULL,
  `sub_total` FLOAT NULL DEFAULT NULL,
  `tax` FLOAT NULL DEFAULT NULL,
  `total` FLOAT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'CLOSE', 'OPEN') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `sales_tax` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sales_orders_id`),
  UNIQUE INDEX `so` (`so` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `sales_orders_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `stone_design`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`so_loading_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`so_loading_order` (
  `so_loading_order_id` INT NOT NULL AUTO_INCREMENT,
  `sales_orders_id` INT NOT NULL,
  `sub_total` FLOAT NULL DEFAULT NULL,
  `tax` FLOAT NULL DEFAULT NULL,
  `total` FLOAT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'CLOSE', 'OPEN') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `sales_status` ENUM('INITIATED', 'LOADING ORDER', 'PACKING LIST', 'INVOICE') NOT NULL DEFAULT 'INITIATED',
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`so_loading_order_id`),
  INDEX `sales_orders_id` (`sales_orders_id` ASC) VISIBLE,
  CONSTRAINT `so_loading_order_ibfk_1`
    FOREIGN KEY (`sales_orders_id`)
    REFERENCES `stone_design`.`sales_orders` (`sales_orders_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`account_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`account_transaction` (
  `account_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_mapper_id` INT NULL DEFAULT NULL,
  `purchase_order_id` INT NULL DEFAULT NULL,
  `supplier_id` INT NULL DEFAULT NULL,
  `so_loading_order_id` INT NULL DEFAULT NULL,
  `so` INT NULL DEFAULT NULL,
  `transaction_of` ENUM('sales', 'purchase') NOT NULL,
  `transaction_amount` FLOAT NULL DEFAULT NULL,
  `transaction_amount_date` DATE NULL DEFAULT NULL,
  `transaction_amount_type` ENUM('debit', 'credit') NOT NULL,
  `accounts_id` INT NOT NULL,
  `entry_type` ENUM('dr', 'cr') NOT NULL,
  `payment_method` VARCHAR(50) NULL DEFAULT NULL,
  `check` INT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `suite` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `zip` INT NULL DEFAULT NULL,
  `memo` VARCHAR(255) NULL DEFAULT NULL,
  `miscellaneous` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `amountOn_check` FLOAT NULL DEFAULT NULL,
  `amount_applied` FLOAT NULL DEFAULT NULL,
  `unapplied_balance` FLOAT NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `vendor_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`account_transaction_id`),
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  INDEX `purchase_order_id` (`purchase_order_id` ASC) VISIBLE,
  INDEX `accounts_id` (`accounts_id` ASC) VISIBLE,
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  INDEX `so_loading_order_id` (`so_loading_order_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `fk_vendor_id_new` (`vendor_id` ASC) VISIBLE,
  CONSTRAINT `account_transaction_ibfk_1`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`),
  CONSTRAINT `account_transaction_ibfk_2`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `stone_design`.`purchase_orders` (`purchase_order_id`),
  CONSTRAINT `account_transaction_ibfk_3`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `stone_design`.`accounts` (`accounts_id`),
  CONSTRAINT `account_transaction_ibfk_4`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `stone_design`.`suppliers` (`supplier_id`),
  CONSTRAINT `account_transaction_ibfk_5`
    FOREIGN KEY (`so_loading_order_id`)
    REFERENCES `stone_design`.`so_loading_order` (`so_loading_order_id`),
  CONSTRAINT `account_transaction_ibfk_7`
    FOREIGN KEY (`customer_id`)
    REFERENCES `stone_design`.`customers` (`customer_id`),
  CONSTRAINT `fk_vendor_id_new`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `stone_design`.`vendors` (`vendor_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 305
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`purchase_order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`purchase_order_products` (
  `purchase_order_product_id` INT NOT NULL AUTO_INCREMENT,
  `purchase_order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`purchase_order_product_id`),
  INDEX `purchase_order_id` (`purchase_order_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `purchase_order_products_ibfk_1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `stone_design`.`purchase_orders` (`purchase_order_id`),
  CONSTRAINT `purchase_order_products_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `stone_design`.`products` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`po_supplier_invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`po_supplier_invoices` (
  `po_supplier_invoice_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_mapper_id` INT NOT NULL,
  `purchase_order_product_id` INT NOT NULL,
  `product_sku` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_notes` VARCHAR(255) NULL DEFAULT NULL,
  `slab` INT NULL DEFAULT NULL,
  `sqm` FLOAT NULL DEFAULT NULL,
  `uom` FLOAT NULL DEFAULT NULL,
  `quantity` FLOAT NULL DEFAULT NULL,
  `unit_price` FLOAT NULL DEFAULT NULL,
  `total_per_unit` FLOAT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`po_supplier_invoice_id`),
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  INDEX `purchase_order_product_id` (`purchase_order_product_id` ASC) VISIBLE,
  INDEX `fk_product_id_one` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_id_one`
    FOREIGN KEY (`product_id`)
    REFERENCES `stone_design`.`products` (`product_id`),
  CONSTRAINT `po_supplier_invoices_ibfk_1`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`),
  CONSTRAINT `po_supplier_invoices_ibfk_2`
    FOREIGN KEY (`purchase_order_product_id`)
    REFERENCES `stone_design`.`purchase_order_products` (`purchase_order_product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`po_slab_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`po_slab_details` (
  `po_slab_detail_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_id` INT NOT NULL,
  `po_supplier_invoice_mapper_id` INT NOT NULL,
  `serial_number` VARCHAR(255) NOT NULL,
  `entry_unit` VARCHAR(255) NULL DEFAULT NULL,
  `package_length` FLOAT NULL DEFAULT NULL,
  `package_width` FLOAT NULL DEFAULT NULL,
  `receving_length` FLOAT NULL DEFAULT NULL,
  `receving_width` FLOAT NULL DEFAULT NULL,
  `block` INT NULL DEFAULT NULL,
  `lot` INT NULL DEFAULT NULL,
  `slab` INT NULL DEFAULT NULL,
  `bin` ENUM('A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6') NOT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  `slab_counter` INT NOT NULL,
  `barcode` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'RETURNED', 'ONHOLD') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `addedToSelectionSheet` TINYINT(1) NOT NULL DEFAULT '0',
  `slabAddedToCart` TINYINT(1) NOT NULL DEFAULT '0',
  `slab_added_to_cart` TINYINT(1) NOT NULL DEFAULT '0',
  `location_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`po_slab_detail_id`),
  INDEX `po_supplier_invoice_id` (`po_supplier_invoice_id` ASC) VISIBLE,
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  INDEX `fk_location_id` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `stone_design`.`locations` (`location_id`),
  CONSTRAINT `po_slab_details_ibfk_1`
    FOREIGN KEY (`po_supplier_invoice_id`)
    REFERENCES `stone_design`.`po_supplier_invoices` (`po_supplier_invoice_id`),
  CONSTRAINT `po_slab_details_ibfk_2`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 661
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`add_to_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`add_to_cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `po_slab_detail_id` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `po_slab_detail_id` (`po_slab_detail_id` ASC) VISIBLE,
  CONSTRAINT `add_to_cart_ibfk_1`
    FOREIGN KEY (`po_slab_detail_id`)
    REFERENCES `stone_design`.`po_slab_details` (`po_slab_detail_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`client_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`client_locations` (
  `client_location_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NULL DEFAULT NULL,
  `location_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`client_location_id`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `location_id` (`location_id` ASC) VISIBLE,
  CONSTRAINT `client_locations_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `stone_design`.`clients` (`client_id`),
  CONSTRAINT `client_locations_ibfk_2`
    FOREIGN KEY (`location_id`)
    REFERENCES `stone_design`.`locations` (`location_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`container`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`container` (
  `container_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_mapper_id` INT NOT NULL,
  `container_number` VARCHAR(255) NOT NULL,
  `received_on` DATETIME NULL DEFAULT NULL,
  `received_by` VARCHAR(255) NOT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`container_id`),
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  CONSTRAINT `container_ibfk_1`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`freight_bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`freight_bills` (
  `freight_bills_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_id` INT NOT NULL,
  `po_supplier_invoice_mapper_id` INT NOT NULL,
  `transaction_id` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `invoice` VARCHAR(255) NULL DEFAULT NULL,
  `invoice_date` DATE NULL DEFAULT NULL,
  `payment_terms` ENUM('30', '45', '60', '90', '120', 'COD') NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `contacts_location` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `address_2` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `state` VARCHAR(100) NULL DEFAULT NULL,
  `zip` VARCHAR(20) NULL DEFAULT NULL,
  `country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `printed_notes` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `sub_total` INT NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `vendor_id` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`freight_bills_id`),
  INDEX `po_supplier_invoice_id` (`po_supplier_invoice_id` ASC) VISIBLE,
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  INDEX `fk_vendor_id` (`vendor_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendor_id`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `stone_design`.`vendors` (`vendor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `freight_bills_ibfk_1`
    FOREIGN KEY (`po_supplier_invoice_id`)
    REFERENCES `stone_design`.`po_supplier_invoices` (`po_supplier_invoice_id`),
  CONSTRAINT `freight_bills_ibfk_2`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`freight_bill_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`freight_bill_details` (
  `detail_id` INT NOT NULL AUTO_INCREMENT,
  `freight_bills_id` INT NOT NULL,
  `accounts_id` INT NULL DEFAULT NULL,
  `locations` VARCHAR(255) NULL DEFAULT NULL,
  `services` VARCHAR(255) NULL DEFAULT NULL,
  `purchased_as` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `extended` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`detail_id`),
  INDEX `freight_bills_id` (`freight_bills_id` ASC) VISIBLE,
  CONSTRAINT `freight_bill_details_ibfk_1`
    FOREIGN KEY (`freight_bills_id`)
    REFERENCES `stone_design`.`freight_bills` (`freight_bills_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`freightbills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`freightbills` (
  `freight_bills_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_id` INT NOT NULL,
  `po_supplier_invoice_mapper_id` INT NOT NULL,
  `transaction_id` VARCHAR(255) NULL DEFAULT NULL,
  `vendor_id` INT NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `invoice` VARCHAR(255) NULL DEFAULT NULL,
  `invoice_date` DATETIME NULL DEFAULT NULL,
  `payment_terms` ENUM('30', '45', '60', '90', '120', 'COD') NULL DEFAULT NULL,
  `due_date` DATETIME NULL DEFAULT NULL,
  `contacts_location` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `address_2` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `zip` VARCHAR(255) NULL DEFAULT NULL,
  `country` ENUM('Vietnam', 'Angola', 'Brazil', 'Canada', 'China', 'Greece', 'India', 'Italy', 'Norway', 'Saudi Arabia', 'South Africa', 'Spain', 'Ukraine') NULL DEFAULT NULL,
  `printed_notes` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `sub_total` INT NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`freight_bills_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`freightbilldetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`freightbilldetails` (
  `detail_id` INT NOT NULL AUTO_INCREMENT,
  `freight_bills_id` INT NOT NULL,
  `accounts_id` INT NULL DEFAULT NULL,
  `locations` VARCHAR(255) NULL DEFAULT NULL,
  `services` VARCHAR(255) NULL DEFAULT NULL,
  `purchased_as` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `extended` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`detail_id`),
  INDEX `freight_bills_id` (`freight_bills_id` ASC) VISIBLE,
  CONSTRAINT `freightbilldetails_ibfk_1`
    FOREIGN KEY (`freight_bills_id`)
    REFERENCES `stone_design`.`freightbills` (`freight_bills_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`product_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`product_inventory` (
  `product_inventory_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `slab_in_stock` FLOAT NULL DEFAULT NULL,
  `quantity_in_stock` FLOAT NULL DEFAULT NULL,
  `slab_available` ENUM('Available') NOT NULL DEFAULT 'Available',
  `quantity_available` ENUM('Available') NOT NULL DEFAULT 'Available',
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_inventory_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_inventory_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stone_design`.`products` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`inventory_invoice_mapper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`inventory_invoice_mapper` (
  `inventory_invoice_mapper_id` INT NOT NULL AUTO_INCREMENT,
  `product_inventory_id` INT NULL DEFAULT NULL,
  `po_supplier_invoice_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`inventory_invoice_mapper_id`),
  INDEX `product_inventory_id` (`product_inventory_id` ASC) VISIBLE,
  INDEX `po_supplier_invoice_id` (`po_supplier_invoice_id` ASC) VISIBLE,
  CONSTRAINT `inventory_invoice_mapper_ibfk_1`
    FOREIGN KEY (`product_inventory_id`)
    REFERENCES `stone_design`.`product_inventory` (`product_inventory_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `inventory_invoice_mapper_ibfk_2`
    FOREIGN KEY (`po_supplier_invoice_id`)
    REFERENCES `stone_design`.`po_supplier_invoices` (`po_supplier_invoice_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`inventory_transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`inventory_transfer` (
  `inventory_transfer_id` INT NOT NULL AUTO_INCREMENT,
  `po_slab_detail_id` INT NULL DEFAULT NULL,
  `initiated_date` DATE NULL DEFAULT NULL,
  `required_ship_date` DATE NULL DEFAULT NULL,
  `eta_date` DATE NULL DEFAULT NULL,
  `delivery_method` ENUM('DELIVERY', 'PICKUP') NOT NULL,
  `shipment_terms` ENUM('Prepaid', 'Prepaid & Add', 'Collect', 'Prepaid & COD', 'Add & COD', 'Collect & COD', 'Credit 45', 'CAD', 'Consignment') NULL DEFAULT NULL,
  `transfer_from` INT NULL DEFAULT NULL,
  `transfer_to` INT NULL DEFAULT NULL,
  `freight_forwarder` ENUM('Ace Drayage', 'Airlift (USA) Inc', 'AJ Worldwide services Inc', 'Avenger Logistics', 'CMA CGM (AMERICA) LLC', 'Crystal Granite (Ocean Freight)', 'DahNAY Logistics', 'Del Corona', 'Edmund Freight', 'Eurybia Logistics Inc', 'Ever Concord Logistics Inc', 'Fortuna Global Logistics LLC', 'Freight Experts Inc', 'General Noli USA Inc', 'Global Logistics & Customs of Charleston', 'Gramazini Freight', 'Heavy Weight Port, Inc', 'Howard Sheppard, Inc', 'Interglobog', 'LAM USA International Transport, LLC', 'Leonardi & Co. USA Inc', 'Optimal Container Logistics', 'Pacific Granites Inc', 'Pacific Quartz (Freight)', 'Patagon Logistics LLC', 'PKD Logistics', 'Savannah River Logistics, LLC', 'SBB Shipping USA Inc', 'Surfaces by Pacific (Freight)', 'Total Quality Logistics (TQL)', 'Tova Trucking, Inc', 'Trans-World Shipping Service, Inc', 'Trident Freight', 'U.S. Customs and Border Protection', 'Western Overseas Corp', 'World-Wide Transportation', 'Worldwide Express Inc', 'Xpress Logistic Solution LLP') NULL DEFAULT NULL,
  `tracking_id` VARCHAR(50) NULL DEFAULT NULL,
  `actual_ship_date` DATE NULL DEFAULT NULL,
  `pick_ticket_restriction` ENUM('Exact Slab', 'Within Lot', 'Within Product') NULL DEFAULT NULL,
  `printed_notes` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`inventory_transfer_id`),
  INDEX `po_slab_detail_id` (`po_slab_detail_id` ASC) VISIBLE,
  CONSTRAINT `inventory_transfer_ibfk_1`
    FOREIGN KEY (`po_slab_detail_id`)
    REFERENCES `stone_design`.`po_slab_details` (`po_slab_detail_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`opportunity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`opportunity` (
  `opportunity_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `op` INT NOT NULL,
  `op_date` DATE NOT NULL,
  `customer_po` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `ship_to` ENUM('DELIVERY', 'PICKUP') NOT NULL,
  `special_instruction` VARCHAR(255) NULL DEFAULT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `printed_notes` VARCHAR(255) NULL DEFAULT NULL,
  `sub_total` FLOAT NULL DEFAULT NULL,
  `tax` FLOAT NULL DEFAULT NULL,
  `total` FLOAT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`opportunity_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `opportunity_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `stone_design`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`opportunity_selection_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`opportunity_selection_sheet` (
  `op_selection_id` INT NOT NULL AUTO_INCREMENT,
  `opportunity_id` INT NOT NULL,
  `product_inventory_id` INT NOT NULL,
  `po_slab_detail_id` INT NOT NULL,
  `status` ENUM('HOLD', 'SALES ORDER') NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `selection_sheet_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`op_selection_id`),
  INDEX `opportunity_id` (`opportunity_id` ASC) VISIBLE,
  INDEX `product_inventory_id` (`product_inventory_id` ASC) VISIBLE,
  INDEX `po_slab_detail_id` (`po_slab_detail_id` ASC) VISIBLE,
  CONSTRAINT `opportunity_selection_sheet_ibfk_1`
    FOREIGN KEY (`opportunity_id`)
    REFERENCES `stone_design`.`opportunity` (`opportunity_id`),
  CONSTRAINT `opportunity_selection_sheet_ibfk_2`
    FOREIGN KEY (`product_inventory_id`)
    REFERENCES `stone_design`.`product_inventory` (`product_inventory_id`),
  CONSTRAINT `opportunity_selection_sheet_ibfk_3`
    FOREIGN KEY (`po_slab_detail_id`)
    REFERENCES `stone_design`.`po_slab_details` (`po_slab_detail_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 186
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`permissions` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `module` VARCHAR(255) NULL DEFAULT NULL,
  `route` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 235
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`pre_purchase_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`pre_purchase_orders` (
  `pre_purchase_order_id` INT NOT NULL AUTO_INCREMENT,
  `purchase_order_product_id` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_note` VARCHAR(255) NULL DEFAULT NULL,
  `purchase_quantity` INT NULL DEFAULT NULL,
  `purchase_uom` VARCHAR(255) NULL DEFAULT NULL,
  `unit_price` FLOAT NULL DEFAULT NULL,
  `minimum_length` FLOAT NULL DEFAULT NULL,
  `minimum_width` FLOAT NULL DEFAULT NULL,
  `bundles` INT NULL DEFAULT NULL,
  `slab_bundles` INT NULL DEFAULT NULL,
  `slabs` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `final_unit_price` FLOAT NULL DEFAULT NULL,
  `total_price` FLOAT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`pre_purchase_order_id`),
  INDEX `purchase_order_product_id` (`purchase_order_product_id` ASC) VISIBLE,
  CONSTRAINT `pre_purchase_orders_ibfk_1`
    FOREIGN KEY (`purchase_order_product_id`)
    REFERENCES `stone_design`.`purchase_order_products` (`purchase_order_product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`product_landed_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`product_landed_cost` (
  `product_landed_cost_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `product_landed_cost` INT NULL DEFAULT NULL,
  `po_supplier_invoice_mapper_id` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`product_landed_cost_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  CONSTRAINT `product_landed_cost_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `stone_design`.`products` (`product_id`)
    ON DELETE SET NULL,
  CONSTRAINT `product_landed_cost_ibfk_2`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`purchase_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`purchase_payment` (
  `purchase_payment_id` INT NOT NULL AUTO_INCREMENT,
  `po_supplier_invoice_mapper_id` INT NULL DEFAULT NULL,
  `supplier_id` INT NOT NULL,
  `cash_account` VARCHAR(255) NOT NULL,
  `payment_date` DATETIME NULL DEFAULT NULL,
  `payment_method` ENUM('Cash', 'Check', 'Debit Card', 'CC-Amex', 'CC-Master', 'CC-Visa', 'CC-Discover', 'Wire', 'ACH', 'AutoPay', 'Other') NOT NULL,
  `check` INT NULL DEFAULT NULL,
  `date_on_check` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `suite` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `zip` INT NULL DEFAULT NULL,
  `memo` VARCHAR(255) NULL DEFAULT NULL,
  `miscellaneous` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `amountOn_check` FLOAT NOT NULL,
  `amount_applied` FLOAT NOT NULL,
  `unapplied_balance` FLOAT NOT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`purchase_payment_id`),
  INDEX `po_supplier_invoice_mapper_id` (`po_supplier_invoice_mapper_id` ASC) VISIBLE,
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `purchase_payment_ibfk_1`
    FOREIGN KEY (`po_supplier_invoice_mapper_id`)
    REFERENCES `stone_design`.`po_supplier_invoice_mapper` (`po_supplier_invoice_mapper_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `purchase_payment_ibfk_2`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `stone_design`.`suppliers` (`supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(255) NOT NULL,
  `role_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`role_permissions` (
  `role_permission_id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NULL DEFAULT NULL,
  `permission_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`role_permission_id`),
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  INDEX `permission_id` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `role_permissions_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `stone_design`.`roles` (`role_id`),
  CONSTRAINT `role_permissions_ibfk_2`
    FOREIGN KEY (`permission_id`)
    REFERENCES `stone_design`.`permissions` (`permission_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sales_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sales_account` (
  `sales_account_id` INT NOT NULL AUTO_INCREMENT,
  `so_loading_order_id` INT NULL DEFAULT NULL,
  `sales_orders_id` INT NULL DEFAULT NULL,
  `debit_amount` INT NULL DEFAULT NULL,
  `debit_amount_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`sales_account_id`),
  INDEX `so_loading_order_id` (`so_loading_order_id` ASC) VISIBLE,
  INDEX `sales_orders_id` (`sales_orders_id` ASC) VISIBLE,
  CONSTRAINT `sales_account_ibfk_1`
    FOREIGN KEY (`so_loading_order_id`)
    REFERENCES `stone_design`.`so_loading_order` (`so_loading_order_id`),
  CONSTRAINT `sales_account_ibfk_2`
    FOREIGN KEY (`sales_orders_id`)
    REFERENCES `stone_design`.`sales_orders` (`sales_orders_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sales_account_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sales_account_transaction` (
  `sales_account_id` INT NOT NULL AUTO_INCREMENT,
  `so_loading_order_id` INT NOT NULL,
  `so` INT NULL DEFAULT NULL,
  `debit_amount` INT NULL DEFAULT NULL,
  `debit_amount_date` DATE NULL DEFAULT NULL,
  `credit_amount` INT NULL DEFAULT NULL,
  `credit_amount_date` DATE NULL DEFAULT NULL,
  `transaction_type` ENUM('debit', 'credit') NOT NULL,
  `accounts_id` INT NOT NULL,
  `entry_type` ENUM('dr', 'cr') NOT NULL,
  PRIMARY KEY (`sales_account_id`),
  INDEX `so_loading_order_id` (`so_loading_order_id` ASC) VISIBLE,
  INDEX `so` (`so` ASC) VISIBLE,
  INDEX `accounts_id` (`accounts_id` ASC) VISIBLE,
  CONSTRAINT `sales_account_transaction_ibfk_1`
    FOREIGN KEY (`so_loading_order_id`)
    REFERENCES `stone_design`.`so_loading_order` (`so_loading_order_id`),
  CONSTRAINT `sales_account_transaction_ibfk_2`
    FOREIGN KEY (`so`)
    REFERENCES `stone_design`.`sales_orders` (`so`),
  CONSTRAINT `sales_account_transaction_ibfk_3`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `stone_design`.`accounts` (`accounts_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sales_credit_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sales_credit_transactions` (
  `sales_credit_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `sales_account_id` INT NULL DEFAULT NULL,
  `credit_amount` INT NULL DEFAULT NULL,
  `credit_amount_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`sales_credit_transaction_id`),
  INDEX `sales_account_id` (`sales_account_id` ASC) VISIBLE,
  CONSTRAINT `sales_credit_transactions_ibfk_1`
    FOREIGN KEY (`sales_account_id`)
    REFERENCES `stone_design`.`sales_account` (`sales_account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sales_orders_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sales_orders_inventory` (
  `sales_orders_inventory_id` INT NOT NULL AUTO_INCREMENT,
  `sales_orders_id` INT NOT NULL,
  `product_inventory_id` INT NULL DEFAULT NULL,
  `po_slab_detail_id` INT NOT NULL,
  `so_loading_order_id` INT NULL DEFAULT NULL,
  `unit_price` FLOAT NULL DEFAULT NULL,
  `sales_status` ENUM('INITIATED', 'LOADING ORDER', 'PACKING LIST', 'INVOICE') NOT NULL DEFAULT 'INITIATED',
  `remeasure_length` FLOAT NULL DEFAULT NULL,
  `remeasure_width` FLOAT NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `slab_picked` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sales_orders_inventory_id`),
  INDEX `sales_orders_id` (`sales_orders_id` ASC) VISIBLE,
  INDEX `product_inventory_id` (`product_inventory_id` ASC) VISIBLE,
  INDEX `po_slab_detail_id` (`po_slab_detail_id` ASC) VISIBLE,
  INDEX `so_loading_order_id` (`so_loading_order_id` ASC) VISIBLE,
  CONSTRAINT `sales_orders_inventory_ibfk_1`
    FOREIGN KEY (`sales_orders_id`)
    REFERENCES `stone_design`.`sales_orders` (`sales_orders_id`),
  CONSTRAINT `sales_orders_inventory_ibfk_2`
    FOREIGN KEY (`product_inventory_id`)
    REFERENCES `stone_design`.`product_inventory` (`product_inventory_id`),
  CONSTRAINT `sales_orders_inventory_ibfk_3`
    FOREIGN KEY (`po_slab_detail_id`)
    REFERENCES `stone_design`.`po_slab_details` (`po_slab_detail_id`),
  CONSTRAINT `sales_orders_inventory_ibfk_4`
    FOREIGN KEY (`so_loading_order_id`)
    REFERENCES `stone_design`.`so_loading_order` (`so_loading_order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 137
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`sales_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`sales_payment` (
  `sales_payment_id` INT NOT NULL AUTO_INCREMENT,
  `so_loading_order_id` INT NOT NULL,
  `sales_orders_id` INT NOT NULL,
  `cash_account` VARCHAR(255) NOT NULL,
  `payment_date` DATE NULL DEFAULT NULL,
  `payment_method` ENUM('Cash', 'Check', 'Debit Card', 'CC-Amex', 'CC-Master', 'CC-Visa', 'CC-Discover', 'Wire', 'ACH', 'AutoPay', 'Other') NOT NULL,
  `check` INT NULL DEFAULT NULL,
  `date_on_check` DATE NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `suite` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `zip` INT NULL DEFAULT NULL,
  `memo` VARCHAR(255) NULL DEFAULT NULL,
  `miscellaneous` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `amountOn_check` FLOAT NOT NULL,
  `amount_applied` FLOAT NOT NULL,
  `unapplied_balance` FLOAT NOT NULL,
  `internal_notes` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`sales_payment_id`),
  INDEX `so_loading_order_id` (`so_loading_order_id` ASC) VISIBLE,
  INDEX `sales_orders_id` (`sales_orders_id` ASC) VISIBLE,
  CONSTRAINT `sales_payment_ibfk_1`
    FOREIGN KEY (`so_loading_order_id`)
    REFERENCES `stone_design`.`so_loading_order` (`so_loading_order_id`),
  CONSTRAINT `sales_payment_ibfk_2`
    FOREIGN KEY (`sales_orders_id`)
    REFERENCES `stone_design`.`sales_orders` (`sales_orders_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`settings` (
  `setting_id` INT NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(255) NOT NULL,
  `setting_value` JSON NOT NULL,
  `setting_type` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`setting_id`),
  UNIQUE INDEX `setting_key` (`setting_key` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`supplier_writing_instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`supplier_writing_instruction` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `beneficiary_name` VARCHAR(255) NOT NULL,
  `beneficiary_address` VARCHAR(255) NOT NULL,
  `beneficiary_phone` VARCHAR(50) NULL DEFAULT NULL,
  `beneficiary_mobile` VARCHAR(50) NULL DEFAULT NULL,
  `beneficiary_fax` VARCHAR(50) NULL DEFAULT NULL,
  `bank_name` VARCHAR(255) NOT NULL,
  `bank_address` VARCHAR(255) NOT NULL,
  `bank_phone` VARCHAR(50) NULL DEFAULT NULL,
  `bank_mobile` VARCHAR(50) NULL DEFAULT NULL,
  `bank_fax` VARCHAR(50) NULL DEFAULT NULL,
  `routing` VARCHAR(50) NULL DEFAULT NULL,
  `account` VARCHAR(50) NULL DEFAULT NULL,
  `swift_code` VARCHAR(50) NULL DEFAULT NULL,
  `iban` VARCHAR(50) NULL DEFAULT NULL,
  `internal_notes` TEXT NULL DEFAULT NULL,
  `supplier_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_writing_instruction_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `stone_design`.`suppliers` (`supplier_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`user_permissions` (
  `user_permission_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `permission_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_permission_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `permission_id` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `user_permissions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stone_design`.`users` (`id`),
  CONSTRAINT `user_permissions_ibfk_2`
    FOREIGN KEY (`permission_id`)
    REFERENCES `stone_design`.`permissions` (`permission_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stone_design`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone_design`.`user_roles` (
  `user_role_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `user_email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_role_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_email` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_user_email`
    FOREIGN KEY (`user_email`)
    REFERENCES `stone_design`.`users` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_roles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stone_design`.`users` (`id`),
  CONSTRAINT `user_roles_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `stone_design`.`roles` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `stone_design` ;

-- -----------------------------------------------------
-- procedure update_coa_codes
-- -----------------------------------------------------

DELIMITER $$
USE `stone_design`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_coa_codes`()
BEGIN
    DECLARE done INT DEFAULT 0;
    DECLARE var_account_id INT;
    DECLARE var_account_types_id INT;
    DECLARE var_sub_account_types_id INT;
    DECLARE var_coa_code VARCHAR(6);
    
    DECLARE account_cursor CURSOR FOR
    SELECT accounts_id, account_types_id, sub_account_types_id
    FROM accounts;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;

    OPEN account_cursor;

    read_loop: LOOP
        FETCH account_cursor INTO var_account_id, var_account_types_id, var_sub_account_types_id;
        
        IF done THEN
            LEAVE read_loop;
        END IF;
        
        SET var_coa_code = CONCAT(
            LPAD(var_account_types_id, 2, '0'),
            LPAD(var_sub_account_types_id, 2, '0'),
            LPAD(var_account_id, 2, '0')
        );

        UPDATE accounts
        SET coa_code = var_coa_code
        WHERE accounts_id = var_account_id;
    END LOOP;

    CLOSE account_cursor;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure update_coa_codes_one_by_one
-- -----------------------------------------------------

DELIMITER $$
USE `stone_design`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_coa_codes_one_by_one`()
BEGIN
    DECLARE done INT DEFAULT 0;
    DECLARE var_account_id INT;
    DECLARE var_account_types_id INT;
    DECLARE var_sub_account_types_id INT;
    DECLARE var_coa_code VARCHAR(12);
    DECLARE var_row_number INT;

    DECLARE account_cursor CURSOR FOR
    SELECT accounts_id, account_types_id, sub_account_types_id
    FROM accounts;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;

    OPEN account_cursor;

    read_loop: LOOP
        FETCH account_cursor INTO var_account_id, var_account_types_id, var_sub_account_types_id;

        IF done THEN
            LEAVE read_loop;
        END IF;

        -- Initialize the row number variable
        SET @row_number := 0;
        
        -- Compute the row number for sub_account_types_id within its account_types_id group
        SELECT row_num
        INTO var_row_number
        FROM (
            SELECT sub_account_types_id, 
                   (@row_number := @row_number + 1) AS row_num
            FROM sub_account_types
            WHERE account_types_id = var_account_types_id
            ORDER BY sub_account_types_id
        ) AS sub_accounts
        WHERE sub_account_types_id = var_sub_account_types_id;

        -- Construct the coa_code
        SET var_coa_code = CONCAT(
            LPAD(CAST(var_account_types_id AS CHAR), 2, '0'),
            LPAD(CAST(var_row_number AS CHAR), 2, '0'),
            LPAD(CAST(var_account_id AS CHAR), 4, '0')
        );

        -- Update the accounts table with the generated coa_code
        UPDATE accounts
        SET coa_code = var_coa_code
        WHERE accounts_id = var_account_id;
    END LOOP;

    CLOSE account_cursor;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
